Attempt to fix initialization errors some users are seeing on Firefox
An user sent in an initialization log with an error:
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 2 ExtensionStorageIDB.jsm:802
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:802
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:699

Which is this line:
https://dxr.mozilla.org/mozilla-central/rev/34d71b4a00863e7615463592662dfe362c4a993e/toolkit/components/extensions/child/ext-storage.js#273

This lead me to believe pref initialization is failing in Firefox for some reason
which breaks the Connector background page initialization